import { execFile } from 'node:child_process'
import { Context, Effect, Layer } from 'effect'
import { DatabaseService } from '../../../infra/database'
import { shellQuote as quote } from '../../../infra/shell-quote'
import { AppError } from '../../../services/errors'
import {
  getWorkspaceAutoGeneratedGlobs,
  listFileReviewMarkers,
  toggleFileReviewMarker,
} from '../repository/file-review'

// --- Errors ---

/**
 * A git command exited non-zero on an operation the user explicitly requested
 * (stage, commit, …). Carries git's stderr through to the client so they see
 * *why* it failed (nothing staged, pre-commit hook rejected, etc.) instead of a
 * generic 500. Maps to HTTP 422 — the request was understood, the operation
 * could not be completed.
 */
export class GitOperationError extends AppError('GitOperationError', 'UNPROCESSABLE_CONTENT')<{
  readonly operation: string
  readonly exitCode: number
  readonly stderr: string
}> {}

// --- Types ---

type GitRepoInfo = {
  repoPath: string
  branch: string | null
}

type GitFileStatus = {
  path: string
  status: 'added' | 'modified' | 'deleted' | 'renamed' | 'untracked'
  staged: boolean
}

type GitStatusResult = {
  branch: string | null
  upstream: string | null
  hasRemote: boolean
  ahead: number
  behind: number
  staged: GitFileStatus[]
  unstaged: GitFileStatus[]
  untracked: string[]
}

type GitDiffResult = {
  diff: string
  files: { path: string; additions: number; deletions: number }[]
  mergeBase?: string
}

type GitDiffStatsResult = {
  files: { path: string; additions: number; deletions: number }[]
  mergeBase?: string
}

/**
 * Everything the git-status broadcaster needs for a single pod in one shot.
 * Produced by a single shell invocation — see `getLocalSnapshot`.
 */
type GitLocalSnapshot = {
  isRepo: boolean
  branch: string | null
  upstream: string | null
  hasRemote: boolean
  ahead: number
  behind: number
  staged: GitFileStatus[]
  unstaged: GitFileStatus[]
  untracked: string[]
  hasWorkingTreeChanges: boolean
  changedFileCount: number
  uncommittedFiles: { path: string; additions: number; deletions: number }[]
  branchFiles: { path: string; additions: number; deletions: number }[]
  mergeBase: string | null
}

type GitBranchInfo = {
  name: string
  current: boolean
  remote?: string
}

type GitWorktreeInfo = {
  path: string
  branch: string | null
  bare: boolean
}

const DEFAULT_AUTO_GENERATED_GLOBS = ['**/*.gen.*']

// --- ShellExec abstraction ---

export type ShellExecFn = (opts: {
  command: string
  cwd?: string
  env?: Record<string, string>
}) => Promise<{ stdout: string; stderr: string; exitCode: number }>

// --- Service shape ---

interface GitControllerShape {
  readonly discover: (path: string, shellExec: ShellExecFn) => Effect.Effect<GitRepoInfo | null>

  readonly getStatus: (repoPath: string, shellExec: ShellExecFn) => Effect.Effect<GitStatusResult>

  readonly getDiff: (
    repoPath: string,
    opts: { mode: 'uncommitted' | 'branch'; baseRef?: string },
    shellExec: ShellExecFn,
  ) => Effect.Effect<GitDiffResult>

  /** Stats-only variant: skips the full unified diff text. Use for badges/totals. */
  readonly getDiffStats: (
    repoPath: string,
    opts: { mode: 'uncommitted' | 'branch'; baseRef?: string },
    shellExec: ShellExecFn,
  ) => Effect.Effect<GitDiffStatsResult>

  /**
   * One-shot snapshot: status + uncommitted numstat + branch numstat + untracked
   * line counts in a single shell invocation. Used by the badge broadcaster to
   * avoid N git spawns per pod per refresh.
   */
  readonly getLocalSnapshot: (
    repoPath: string,
    baseRef: string | undefined,
    shellExec: ShellExecFn,
  ) => Effect.Effect<GitLocalSnapshot>

  readonly listBranches: (repoPath: string, shellExec: ShellExecFn) => Effect.Effect<GitBranchInfo[]>

  readonly listWorktrees: (repoPath: string, shellExec: ShellExecFn) => Effect.Effect<GitWorktreeInfo[]>

  readonly listRemoteBranches: (repoUrl: string) => Effect.Effect<string[]>

  readonly getFileContent: (
    repoPath: string,
    filePath: string,
    ref: string | undefined,
    shellExec: ShellExecFn,
  ) => Effect.Effect<string | null>

  readonly stageFiles: (
    repoPath: string,
    files: string[],
    shellExec: ShellExecFn,
  ) => Effect.Effect<void, GitOperationError>
  readonly unstageFiles: (
    repoPath: string,
    files: string[],
    shellExec: ShellExecFn,
  ) => Effect.Effect<void, GitOperationError>
  readonly stageAll: (repoPath: string, shellExec: ShellExecFn) => Effect.Effect<void, GitOperationError>
  readonly unstageAll: (repoPath: string, shellExec: ShellExecFn) => Effect.Effect<void, GitOperationError>
  readonly commit: (
    repoPath: string,
    message: string,
    shellExec: ShellExecFn,
  ) => Effect.Effect<{ hash: string }, GitOperationError>
  readonly push: (
    repoPath: string,
    shellExec: ShellExecFn,
    opts?: { setUpstream?: boolean; force?: boolean },
  ) => Effect.Effect<{ success: boolean; error?: string }>
  readonly pull: (repoPath: string, shellExec: ShellExecFn) => Effect.Effect<{ success: boolean; error?: string }>
  readonly createBranch: (
    repoPath: string,
    branchName: string,
    shellExec: ShellExecFn,
  ) => Effect.Effect<{ success: boolean; error?: string }>
  readonly checkoutBranch: (
    repoPath: string,
    branchName: string,
    shellExec: ShellExecFn,
  ) => Effect.Effect<{ success: boolean; error?: string }>
  /** Checkout branch, pull, stashing uncommitted changes if needed */
  readonly checkoutAndPull: (
    repoPath: string,
    branchName: string,
    shellExec: ShellExecFn,
  ) => Effect.Effect<{ success: boolean; stashed: boolean; error?: string }>

  readonly toggleFileViewed: (
    podId: string,
    filePath: string,
    repoPath: string,
    shellExec: ShellExecFn,
  ) => Effect.Effect<{ viewed: boolean }>

  readonly getAutoGeneratedPatterns: (
    repoPath: string,
    workspaceId: string | null,
    shellExec: ShellExecFn | null,
  ) => Effect.Effect<string[]>

  readonly listViewedFiles: (
    podId: string,
    filePaths: string[],
    repoPath: string,
    shellExec: ShellExecFn,
  ) => Effect.Effect<string[]>
}

export class GitController extends Context.Tag('GitController')<GitController, GitControllerShape>() {}

export const GitControllerLive = Layer.effect(
  GitController,
  Effect.gen(function* () {
    const db = yield* DatabaseService

    function git(shellExec: ShellExecFn, repoPath: string, args: string) {
      return shellExec({ command: `git -C ${quote(repoPath)} ${args}` })
    }

    function resolveDiffCmd(
      shellExec: ShellExecFn,
      repoPath: string,
      opts: { mode: 'uncommitted' | 'branch'; baseRef?: string },
    ) {
      return Effect.gen(function* () {
        if (opts.mode === 'uncommitted') {
          return { diffCmd: 'diff HEAD', resolvedMergeBase: undefined as string | undefined }
        }
        const baseRef = opts.baseRef ?? 'main'
        const mergeBaseResult = yield* Effect.promise(() =>
          git(shellExec, repoPath, `merge-base ${quote(baseRef)} HEAD`),
        )
        const resolvedMergeBase = mergeBaseResult.exitCode === 0 ? mergeBaseResult.stdout.trim() : baseRef
        return { diffCmd: `diff ${quote(resolvedMergeBase)}`, resolvedMergeBase }
      })
    }

    function collectDiffFiles(shellExec: ShellExecFn, repoPath: string, diffCmd: string) {
      return Effect.gen(function* () {
        const numstatResult = yield* Effect.promise(() => git(shellExec, repoPath, `${diffCmd} --numstat`))

        const files: { path: string; additions: number; deletions: number }[] = []
        if (numstatResult.exitCode === 0) {
          for (const line of numstatResult.stdout.split('\n')) {
            if (!line) continue
            const [add, del, path] = line.split('\t')
            if (path) {
              files.push({
                path,
                additions: add === '-' ? 0 : Number.parseInt(add ?? '0', 10),
                deletions: del === '-' ? 0 : Number.parseInt(del ?? '0', 10),
              })
            }
          }
        }

        // Include untracked files — git diff alone never sees them, so the
        // topbar pill / panel totals would otherwise undercount work in progress.
        const statusResult = yield* Effect.promise(() => git(shellExec, repoPath, 'status --porcelain=v1 -uall'))
        if (statusResult.exitCode === 0) {
          const untrackedPaths: string[] = []
          for (const line of statusResult.stdout.split('\n')) {
            if (line.startsWith('??')) untrackedPaths.push(line.slice(3))
          }
          if (untrackedPaths.length > 0) {
            const wcResult = yield* Effect.promise(() =>
              shellExec({
                command: `cd ${quote(repoPath)} && cat ${untrackedPaths.map(quote).join(' ')} 2>/dev/null | wc -l`,
              }),
            )
            if (wcResult.exitCode === 0) {
              const totalLines = Number.parseInt(wcResult.stdout.trim(), 10) || 0
              const perFileResult = yield* Effect.promise(() =>
                shellExec({
                  command: `cd ${quote(repoPath)} && wc -l ${untrackedPaths.map(quote).join(' ')}`,
                }),
              )
              if (perFileResult.exitCode === 0 && untrackedPaths.length > 1) {
                for (const wcLine of perFileResult.stdout.trim().split('\n')) {
                  const match = wcLine.trim().match(/^(\d+)\s+(.+)$/)
                  if (match && match[2] && match[2] !== 'total') {
                    files.push({ path: match[2], additions: Number.parseInt(match[1] ?? '0', 10), deletions: 0 })
                  }
                }
              } else if (untrackedPaths.length === 1 && untrackedPaths[0]) {
                files.push({ path: untrackedPaths[0], additions: totalLines, deletions: 0 })
              }
            }
          }
        }

        return { files }
      })
    }

    return {
      discover: (path, shellExec) =>
        Effect.gen(function* () {
          const result = yield* Effect.promise(() =>
            shellExec({ command: `git -C ${quote(path)} rev-parse --show-toplevel` }),
          )
          if (result.exitCode !== 0) return null

          const repoPath = result.stdout.trim()
          if (!repoPath) return null

          const branchResult = yield* Effect.promise(() => git(shellExec, repoPath, 'rev-parse --abbrev-ref HEAD'))
          const branch = branchResult.exitCode === 0 ? branchResult.stdout.trim() : null

          return { repoPath, branch: branch === 'HEAD' ? null : branch }
        }),

      getStatus: (repoPath, shellExec) =>
        Effect.gen(function* () {
          const branchResult = yield* Effect.promise(() => git(shellExec, repoPath, 'rev-parse --abbrev-ref HEAD'))
          const branch =
            branchResult.exitCode === 0
              ? branchResult.stdout.trim() === 'HEAD'
                ? null
                : branchResult.stdout.trim()
              : null

          const upstreamResult = yield* Effect.promise(() => git(shellExec, repoPath, 'rev-parse --abbrev-ref @{u}'))
          const upstream = upstreamResult.exitCode === 0 ? upstreamResult.stdout.trim() : null

          const remoteResult = yield* Effect.promise(() => git(shellExec, repoPath, 'remote'))
          const hasRemote = remoteResult.exitCode === 0 && remoteResult.stdout.trim().length > 0

          let ahead = 0
          let behind = 0
          if (upstream) {
            const aheadResult = yield* Effect.promise(() => git(shellExec, repoPath, 'rev-list --count @{u}..HEAD'))
            ahead = aheadResult.exitCode === 0 ? Number.parseInt(aheadResult.stdout.trim(), 10) || 0 : 0
            const behindResult = yield* Effect.promise(() => git(shellExec, repoPath, 'rev-list --count HEAD..@{u}'))
            behind = behindResult.exitCode === 0 ? Number.parseInt(behindResult.stdout.trim(), 10) || 0 : 0
          }

          const statusResult = yield* Effect.promise(() => git(shellExec, repoPath, 'status --porcelain=v1 -uall'))

          const staged: GitFileStatus[] = []
          const unstaged: GitFileStatus[] = []
          const untracked: string[] = []

          if (statusResult.exitCode === 0) {
            for (const line of statusResult.stdout.split('\n')) {
              if (!line) continue
              const x = line[0] ?? ' ' // index status
              const y = line[1] ?? ' ' // worktree status
              const filePath = line.slice(3)

              if (x === '?' && y === '?') {
                untracked.push(filePath)
                continue
              }

              if (x !== ' ' && x !== '?') {
                staged.push({ path: filePath, status: parseStatusChar(x), staged: true })
              }
              if (y !== ' ' && y !== '?') {
                unstaged.push({ path: filePath, status: parseStatusChar(y), staged: false })
              }
            }
          }

          return { branch, upstream, hasRemote, ahead, behind, staged, unstaged, untracked }
        }),

      getDiff: (repoPath, opts, shellExec) =>
        Effect.gen(function* () {
          const { diffCmd, resolvedMergeBase } = yield* resolveDiffCmd(shellExec, repoPath, opts)
          const diffResult = yield* Effect.promise(() => git(shellExec, repoPath, diffCmd))
          const { files } = yield* collectDiffFiles(shellExec, repoPath, diffCmd)
          return { diff: diffResult.stdout, files, mergeBase: resolvedMergeBase }
        }),

      getDiffStats: (repoPath, opts, shellExec) =>
        Effect.gen(function* () {
          const { diffCmd, resolvedMergeBase } = yield* resolveDiffCmd(shellExec, repoPath, opts)
          const { files } = yield* collectDiffFiles(shellExec, repoPath, diffCmd)
          return { files, mergeBase: resolvedMergeBase }
        }),

      getLocalSnapshot: (repoPath, baseRef, shellExec) =>
        Effect.gen(function* () {
          const script = buildSnapshotScript(repoPath, baseRef ?? 'main')
          const result = yield* Effect.tryPromise({
            try: () => shellExec({ command: script }),
            catch: (err) => (err instanceof Error ? err : new Error(String(err))),
          }).pipe(Effect.catchAll(() => Effect.succeed({ stdout: '', stderr: '', exitCode: 1 })))
          return parseSnapshot(result.stdout)
        }),

      listBranches: (repoPath, shellExec) =>
        Effect.gen(function* () {
          const result = yield* Effect.promise(() =>
            git(shellExec, repoPath, 'branch -a --format=%(refname:short)%09%(HEAD)%09%(upstream:short)'),
          )

          if (result.exitCode !== 0) return []

          const branches: GitBranchInfo[] = []
          for (const line of result.stdout.split('\n')) {
            if (!line) continue
            const [name, head, remote] = line.split('\t')
            if (name) {
              branches.push({
                name,
                current: head === '*',
                remote: remote || undefined,
              })
            }
          }

          return branches
        }),

      listWorktrees: (repoPath, shellExec) =>
        Effect.gen(function* () {
          const result = yield* Effect.promise(() => git(shellExec, repoPath, 'worktree list --porcelain'))

          if (result.exitCode !== 0) return []

          const worktrees: GitWorktreeInfo[] = []
          let current: Partial<GitWorktreeInfo> = {}

          for (const line of result.stdout.split('\n')) {
            if (line.startsWith('worktree ')) {
              if (current.path) worktrees.push(current as GitWorktreeInfo)
              current = { path: line.slice(9), branch: null, bare: false }
            } else if (line.startsWith('branch ')) {
              current.branch = line.slice(7).replace('refs/heads/', '')
            } else if (line === 'bare') {
              current.bare = true
            } else if (line === '') {
              if (current.path) worktrees.push(current as GitWorktreeInfo)
              current = {}
            }
          }
          if (current.path) worktrees.push(current as GitWorktreeInfo)

          return worktrees
        }),

      listRemoteBranches: (repoUrl) =>
        Effect.tryPromise({
          try: () =>
            new Promise<string[]>((resolve) => {
              const child = execFile('git', ['ls-remote', '--heads', repoUrl], { timeout: 10_000 }, (err, stdout) => {
                if (err) {
                  resolve([])
                  return
                }
                const branches = stdout
                  .split('\n')
                  .map((line) => line.match(/refs\/heads\/(.+)$/)?.[1])
                  .filter((b): b is string => !!b)
                resolve(branches)
              })
              child.on('error', () => resolve([]))
            }),
          catch: () => [] as string[],
        }).pipe(Effect.catchAll(() => Effect.succeed([] as string[]))),

      getFileContent: (repoPath, filePath, ref, shellExec) =>
        Effect.gen(function* () {
          if (ref != null) {
            const result = yield* Effect.promise(() => git(shellExec, repoPath, `show ${quote(`${ref}:${filePath}`)}`))
            return result.exitCode === 0 ? result.stdout : null
          }
          const result = yield* Effect.promise(() => shellExec({ command: `cat ${quote(`${repoPath}/${filePath}`)}` }))
          return result.exitCode === 0 ? result.stdout : null
        }),

      stageFiles: (repoPath, files, shellExec) =>
        Effect.gen(function* () {
          if (files.length === 0) return
          const quoted = files.map((f) => quote(f)).join(' ')
          const result = yield* Effect.promise(() => git(shellExec, repoPath, `add -- ${quoted}`))
          if (result.exitCode !== 0) {
            return yield* gitOpFailed('git add', result)
          }
        }),

      unstageFiles: (repoPath, files, shellExec) =>
        Effect.gen(function* () {
          if (files.length === 0) return
          const quoted = files.map((f) => quote(f)).join(' ')
          const result = yield* Effect.promise(() => git(shellExec, repoPath, `restore --staged -- ${quoted}`))
          if (result.exitCode !== 0) {
            return yield* gitOpFailed('git restore --staged', result)
          }
        }),

      stageAll: (repoPath, shellExec) =>
        Effect.gen(function* () {
          const result = yield* Effect.promise(() => git(shellExec, repoPath, 'add -A'))
          if (result.exitCode !== 0) {
            return yield* gitOpFailed('git add -A', result)
          }
        }),

      unstageAll: (repoPath, shellExec) =>
        Effect.gen(function* () {
          const result = yield* Effect.promise(() => git(shellExec, repoPath, 'reset HEAD'))
          if (result.exitCode !== 0) {
            return yield* gitOpFailed('git reset HEAD', result)
          }
        }),

      commit: (repoPath, message, shellExec) =>
        Effect.gen(function* () {
          const result = yield* Effect.promise(() => git(shellExec, repoPath, `commit -m ${quote(message)}`))
          if (result.exitCode !== 0) {
            return yield* gitOpFailed('git commit', result)
          }
          // Parse commit hash from output like "[branch abc1234] message"
          const match = result.stdout.match(/\[[\w/.-]+ ([a-f0-9]+)\]/)
          return { hash: match?.[1] ?? 'unknown' }
        }),

      push: (repoPath, shellExec, opts) =>
        Effect.gen(function* () {
          const args = ['push']
          if (opts?.force) args.push('--force-with-lease')
          const result = yield* Effect.promise(() => git(shellExec, repoPath, args.join(' ')))

          if (result.exitCode !== 0) {
            // Normalize newlines — git wraps long error messages across lines
            const stderr = result.stderr.replace(/\n/g, ' ')
            // If no upstream or branch name mismatch, retry with explicit branch
            if (
              !opts?.setUpstream &&
              (stderr.includes('no upstream branch') ||
                stderr.includes('does not match the name of your current branch'))
            ) {
              const branchResult = yield* Effect.promise(() => git(shellExec, repoPath, 'rev-parse --abbrev-ref HEAD'))
              const branch = branchResult.stdout.trim()
              const retryResult = yield* Effect.promise(() =>
                git(shellExec, repoPath, `push --set-upstream origin ${quote(branch)}`),
              )
              if (retryResult.exitCode !== 0) {
                return { success: false, error: retryResult.stderr.trim() || 'Push failed' }
              }
              return { success: true }
            }
            return { success: false, error: stderr.trim() || 'Push failed' }
          }
          return { success: true }
        }),

      pull: (repoPath, shellExec) =>
        Effect.gen(function* () {
          const result = yield* Effect.promise(() => git(shellExec, repoPath, 'pull --rebase'))
          if (result.exitCode !== 0) {
            return { success: false, error: result.stderr.trim() || 'Pull failed' }
          }
          return { success: true }
        }),

      createBranch: (repoPath, branchName, shellExec) =>
        Effect.gen(function* () {
          const result = yield* Effect.promise(() => git(shellExec, repoPath, `checkout -b ${quote(branchName)}`))
          if (result.exitCode !== 0) {
            return { success: false, error: result.stderr.trim() || 'Failed to create branch' }
          }
          return { success: true }
        }),

      checkoutBranch: (repoPath, branchName, shellExec) =>
        Effect.gen(function* () {
          const result = yield* Effect.promise(() => git(shellExec, repoPath, `checkout ${quote(branchName)}`))
          if (result.exitCode !== 0) {
            return { success: false, error: result.stderr.trim() || 'Failed to checkout branch' }
          }
          return { success: true }
        }),

      checkoutAndPull: (repoPath, branchName, shellExec) =>
        Effect.gen(function* () {
          // If already on the target branch, skip checkout (and the stash dance).
          const headResult = yield* Effect.promise(() => git(shellExec, repoPath, 'rev-parse --abbrev-ref HEAD'))
          const currentBranch = headResult.exitCode === 0 ? headResult.stdout.trim() : null
          const alreadyOnTarget = currentBranch === branchName

          const statusResult = yield* Effect.promise(() => git(shellExec, repoPath, 'status --porcelain=v1'))
          const isDirty = statusResult.exitCode === 0 && statusResult.stdout.trim().length > 0

          // Stash if dirty AND we actually need to checkout (stashing is unnecessary when staying put).
          let stashed = false
          if (isDirty && !alreadyOnTarget) {
            const stashResult = yield* Effect.promise(() =>
              git(shellExec, repoPath, 'stash push -u -m "auto-stash before checkout"'),
            )
            stashed = stashResult.exitCode === 0 && !stashResult.stdout.includes('No local changes')
          }

          if (!alreadyOnTarget) {
            const checkoutResult = yield* Effect.promise(() =>
              git(shellExec, repoPath, `checkout ${quote(branchName)}`),
            )
            if (checkoutResult.exitCode !== 0) {
              // Restore stash if checkout failed
              if (stashed) yield* Effect.promise(() => git(shellExec, repoPath, 'stash pop'))
              return { success: false, stashed: false, error: checkoutResult.stderr.trim() || 'Failed to checkout' }
            }
          }

          const pullResult = yield* Effect.promise(() => git(shellExec, repoPath, 'pull --rebase'))
          if (pullResult.exitCode !== 0) {
            // Pull failed but checkout succeeded — still on the new branch
            if (stashed) yield* Effect.promise(() => git(shellExec, repoPath, 'stash pop'))
            return { success: true, stashed, error: `Checked out but pull failed: ${pullResult.stderr.trim()}` }
          }

          if (stashed) {
            const popResult = yield* Effect.promise(() => git(shellExec, repoPath, 'stash pop'))
            if (popResult.exitCode !== 0) {
              return {
                success: true,
                stashed: true,
                error: 'Changes stashed but could not be restored — run git stash pop manually',
              }
            }
          }

          return { success: true, stashed }
        }),

      toggleFileViewed: (podId, filePath, repoPath, shellExec) =>
        Effect.gen(function* () {
          const hashResult = yield* Effect.promise(() =>
            shellExec({
              command: `git -C ${quote(repoPath)} hash-object -- ${quote(filePath)}`,
            }),
          )
          if (hashResult.exitCode !== 0) return { viewed: false }
          const contentHash = hashResult.stdout.trim()
          if (!contentHash) return { viewed: false }

          const viewed = toggleFileReviewMarker(db, {
            podId,
            filePath,
            contentHash,
          })
          return { viewed }
        }),

      getAutoGeneratedPatterns: (repoPath, workspaceId, shellExec) =>
        Effect.gen(function* () {
          let userPatterns = DEFAULT_AUTO_GENERATED_GLOBS
          if (workspaceId) {
            userPatterns = getWorkspaceAutoGeneratedGlobs(db, workspaceId) ?? DEFAULT_AUTO_GENERATED_GLOBS
          }

          let gitAttrPatterns: string[] = []
          if (shellExec) {
            const result = yield* Effect.promise(() =>
              shellExec({ command: `cat ${quote(`${repoPath}/.gitattributes`)}` }),
            )
            if (result.exitCode === 0) {
              gitAttrPatterns = parseGitAttributesForGenerated(result.stdout)
            }
          }

          const seen = new Set<string>()
          const combined: string[] = []
          for (const pattern of [...gitAttrPatterns, ...userPatterns]) {
            if (seen.has(pattern)) continue
            seen.add(pattern)
            combined.push(pattern)
          }
          return combined
        }),

      listViewedFiles: (podId, filePaths, repoPath, shellExec) =>
        Effect.gen(function* () {
          if (filePaths.length === 0) return [] as string[]

          const markers = listFileReviewMarkers(db, podId, filePaths)
          if (markers.length === 0) return [] as string[]

          const viewed: string[] = []
          for (const marker of markers) {
            const result = yield* Effect.promise(() =>
              shellExec({
                command: `git -C ${quote(repoPath)} hash-object -- ${quote(marker.filePath)}`,
              }),
            )
            if (result.exitCode !== 0) continue
            const current = result.stdout.trim()
            if (current && current === marker.contentHash) {
              viewed.push(marker.filePath)
            }
          }
          return viewed
        }),
    }
  }),
)

function gitOpFailed(operation: string, result: { stderr: string; exitCode: number }) {
  const stderr = result.stderr.trim()
  return new GitOperationError({
    operation,
    exitCode: result.exitCode,
    stderr,
    message: stderr || `${operation} failed (exit ${result.exitCode})`,
  })
}

function parseStatusChar(c: string): GitFileStatus['status'] {
  switch (c) {
    case 'A':
      return 'added'
    case 'M':
      return 'modified'
    case 'D':
      return 'deleted'
    case 'R':
      return 'renamed'
    default:
      return 'modified'
  }
}

function parseGitAttributesForGenerated(contents: string): string[] {
  const patterns: string[] = []
  for (const rawLine of contents.split('\n')) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue

    const parts = line.split(/\s+/)
    if (parts.length < 2) continue
    const [pattern, ...attrs] = parts
    if (!pattern) continue
    let generated = false
    for (const attr of attrs) {
      if (attr === 'linguist-generated' || attr === 'linguist-generated=true') {
        generated = true
        break
      }
      if (attr === '-linguist-generated' || attr === 'linguist-generated=false') {
        generated = false
        break
      }
    }
    if (generated) patterns.push(pattern)
  }
  return patterns
}

// -----------------------------------------------------------------------------
// Consolidated local-snapshot script — one shell call produces every value the
// badge broadcaster needs. Sections are delimited by a sentinel line that
// cannot appear in git's output (git never emits lines starting with `===`).
// -----------------------------------------------------------------------------

const SNAPSHOT_SEP = '===WANDA-GIT-SECTION==='

function buildSnapshotScript(repoPath: string, baseRef: string): string {
  const cdPath = quote(repoPath)
  const base = quote(baseRef)
  // Single-quoted printf strings — `\n` is expanded by printf, not the shell.
  return [
    `cd ${cdPath} 2>/dev/null || exit 0`,
    `git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 0`,
    `printf '${SNAPSHOT_SEP}BRANCH\\n'`,
    `git rev-parse --abbrev-ref HEAD 2>/dev/null`,
    `printf '${SNAPSHOT_SEP}UPSTREAM\\n'`,
    `git rev-parse --abbrev-ref '@{u}' 2>/dev/null`,
    `printf '${SNAPSHOT_SEP}REMOTES\\n'`,
    `git remote 2>/dev/null`,
    `printf '${SNAPSHOT_SEP}AHEAD_BEHIND\\n'`,
    // left-right count of @{u}...HEAD → "<behind>\t<ahead>"
    `git rev-list --left-right --count '@{u}...HEAD' 2>/dev/null`,
    `STATUS=$(git status --porcelain=2 --branch -uall 2>/dev/null)`,
    `printf '${SNAPSHOT_SEP}STATUS\\n%s\\n' "$STATUS"`,
    `printf '${SNAPSHOT_SEP}UNCOMMITTED_NUMSTAT\\n'`,
    `git diff HEAD --numstat 2>/dev/null`,
    `MB=$(git merge-base ${base} HEAD 2>/dev/null)`,
    `printf '${SNAPSHOT_SEP}MERGE_BASE\\n%s\\n' "$MB"`,
    `printf '${SNAPSHOT_SEP}BRANCH_NUMSTAT\\n'`,
    `[ -n "$MB" ] && git diff "$MB" --numstat 2>/dev/null`,
    `printf '${SNAPSHOT_SEP}UNTRACKED_LINECOUNTS\\n'`,
    // Emit "<lines>\t<path>" per untracked file. Done inline to avoid a
    // second round-trip for line counting.
    `printf '%s\\n' "$STATUS" | awk '/^\\? /{sub(/^\\? /,""); print}' | while IFS= read -r f; do [ -f "$f" ] && printf '%s\\t%s\\n' "$(wc -l < "$f" 2>/dev/null || echo 0)" "$f"; done`,
    `printf '${SNAPSHOT_SEP}END\\n'`,
  ].join('\n')
}

function parseSnapshot(output: string): GitLocalSnapshot {
  const sections = splitSnapshotSections(output)
  const isRepo = Object.hasOwn(sections, 'BRANCH') || Object.hasOwn(sections, 'STATUS')

  const branch = (sections.BRANCH ?? '').trim() || null
  const upstream = (sections.UPSTREAM ?? '').trim() || null
  const hasRemote = (sections.REMOTES ?? '').trim().length > 0

  let ahead = 0
  let behind = 0
  const ab = (sections.AHEAD_BEHIND ?? '').trim()
  if (ab) {
    // "<behind>\t<ahead>" from rev-list --left-right --count A...B where A=@{u}, B=HEAD
    const [b, a] = ab.split(/\s+/)
    behind = Number.parseInt(b ?? '', 10) || 0
    ahead = Number.parseInt(a ?? '', 10) || 0
  }

  const staged: GitFileStatus[] = []
  const unstaged: GitFileStatus[] = []
  const untracked: string[] = []
  const changedPaths = new Set<string>()
  for (const line of (sections.STATUS ?? '').split('\n')) {
    if (!line) continue
    if (line.startsWith('#')) continue
    if (line.startsWith('? ')) {
      const filePath = line.slice(2)
      untracked.push(filePath)
      changedPaths.add(filePath)
      continue
    }
    if (line.startsWith('! ')) continue

    const parsed = parsePorcelainV2Change(line)
    if (!parsed) continue
    const { x, y, filePath } = parsed
    changedPaths.add(filePath)

    if (x !== '.' && x !== '?') {
      staged.push({ path: filePath, status: parseStatusChar(x), staged: true })
    }
    if (y !== '.' && y !== '?') {
      unstaged.push({ path: filePath, status: parseStatusChar(y), staged: false })
    }
  }

  const uncommittedFiles = parseNumstat(sections.UNCOMMITTED_NUMSTAT ?? '')
  const branchFiles = parseNumstat(sections.BRANCH_NUMSTAT ?? '')

  // Untracked line counts — merge into both diff views, matching the previous
  // behaviour where untracked files count as work-in-progress.
  const untrackedStats: { path: string; additions: number; deletions: number }[] = []
  for (const line of (sections.UNTRACKED_LINECOUNTS ?? '').split('\n')) {
    if (!line) continue
    const tab = line.indexOf('\t')
    if (tab < 0) continue
    const n = Number.parseInt(line.slice(0, tab), 10) || 0
    const p = line.slice(tab + 1)
    if (p) untrackedStats.push({ path: p, additions: n, deletions: 0 })
  }
  if (untrackedStats.length > 0) {
    uncommittedFiles.push(...untrackedStats)
    branchFiles.push(...untrackedStats)
  }
  backfillChangedFiles(uncommittedFiles, changedPaths)
  backfillChangedFiles(branchFiles, changedPaths)

  const mergeBase = (sections.MERGE_BASE ?? '').trim() || null

  return {
    isRepo,
    branch: branch === 'HEAD' ? null : branch,
    upstream,
    hasRemote,
    ahead,
    behind,
    staged,
    unstaged,
    untracked,
    hasWorkingTreeChanges: changedPaths.size > 0,
    changedFileCount: changedPaths.size,
    uncommittedFiles,
    branchFiles,
    mergeBase,
  }
}

function parsePorcelainV2Change(line: string): { x: string; y: string; filePath: string } | null {
  const kind = line[0]
  if (kind !== '1' && kind !== '2' && kind !== 'u') return null
  const x = line[2] ?? '.'
  const y = line[3] ?? '.'
  const pathStart = indexAfterFields(line, kind === 'u' ? 10 : kind === '2' ? 9 : 8)
  if (pathStart < 0) return null
  const pathField = line.slice(pathStart)
  const tab = pathField.indexOf('\t')
  const filePath = tab >= 0 ? pathField.slice(0, tab) : pathField
  if (!filePath) return null
  return { x, y, filePath }
}

function indexAfterFields(line: string, fields: number): number {
  let seen = 0
  for (let i = 0; i < line.length; i++) {
    if (line[i] !== ' ') continue
    seen++
    if (seen === fields) return i + 1
  }
  return -1
}

function backfillChangedFiles(
  files: { path: string; additions: number; deletions: number }[],
  changedPaths: ReadonlySet<string>,
) {
  const seen = new Set(files.map((file) => file.path))
  for (const path of changedPaths) {
    if (seen.has(path)) continue
    files.push({ path, additions: 0, deletions: 0 })
  }
}

function splitSnapshotSections(output: string): Record<string, string> {
  const sections: Record<string, string> = {}
  let currentKey: string | null = null
  let buf: string[] = []
  for (const line of output.split('\n')) {
    if (line.startsWith(SNAPSHOT_SEP)) {
      if (currentKey) sections[currentKey] = buf.join('\n')
      currentKey = line.slice(SNAPSHOT_SEP.length)
      buf = []
    } else if (currentKey) {
      buf.push(line)
    }
  }
  if (currentKey) sections[currentKey] = buf.join('\n')
  return sections
}

function parseNumstat(output: string): { path: string; additions: number; deletions: number }[] {
  const files: { path: string; additions: number; deletions: number }[] = []
  for (const line of output.split('\n')) {
    if (!line) continue
    const [add, del, path] = line.split('\t')
    if (path) {
      files.push({
        path,
        additions: add === '-' ? 0 : Number.parseInt(add ?? '0', 10) || 0,
        deletions: del === '-' ? 0 : Number.parseInt(del ?? '0', 10) || 0,
      })
    }
  }
  return files
}
