import { z } from 'zod'
import { WorkspaceSettingsController } from '../../services'
import type { AppRouterDeps } from '../index'

export function workspaceSettingsRoutes({ effectOs, gitStatusBroadcaster }: AppRouterDeps) {
  return {
    getByWorkspace: effectOs.input(z.object({ workspaceId: z.string() })).effect(function* ({ input }) {
      const svc = yield* WorkspaceSettingsController
      return (yield* svc.getByWorkspace(input.workspaceId)) ?? null
    }),

    update: effectOs
      .input(
        z.object({
          workspaceId: z.string(),
          defaultTemplatePodId: z.string().nullable().optional(),
          defaultWorkenvTemplateId: z.string().nullable().optional(),
          autoGeneratePodName: z.boolean().optional(),
          defaultRuntime: z.enum(['pty', 'docker']).nullable().optional(),
          gitWorktreeEnabled: z.boolean().optional(),
          gitWorktreeCopyHiddenFiles: z.boolean().optional(),
          worktreeLocationMode: z.enum(['app-default', 'alongside', 'custom']).nullable().optional(),
          worktreeBaseDir: z.string().nullable().optional(),
          branchFrom: z.string().nullable().optional(),
          remoteOrigin: z.string().nullable().optional(),
          scriptSetup: z.string().nullable().optional(),
          scriptRun: z.string().nullable().optional(),
          scriptArchive: z.string().nullable().optional(),
          autoGeneratedGlobs: z.array(z.string()).nullable().optional(),
          wandaMcpPolicy: z.enum(['inherit', 'include', 'exclude']).nullable().optional(),
          graphiteEnabled: z.boolean().optional(),
          graphiteDefaultCommit: z.enum(['modify', 'newCommit', 'create']).optional(),
          graphiteDefaultPush: z.enum(['submitStack', 'submitCurrent', 'gitPush']).optional(),
          graphiteDefaultPull: z.enum(['sync', 'gitPull']).optional(),
          graphiteDefaultBranch: z.enum(['create', 'gitCheckoutB']).optional(),
        }),
      )
      .effect(function* ({ input }) {
        const svc = yield* WorkspaceSettingsController
        const { workspaceId, ...data } = input
        const settings = yield* svc.upsert(workspaceId, data)
        gitStatusBroadcaster?.invalidateWorkspaceGraphite(workspaceId)
        return settings
      }),
  }
}
