// -----------------------------------------------------------------------------
// Electron preload entry.
//
// Installs `window.wanda` via the WS transport. The main process passes
// the server URL + token via webPreferences.additionalArguments on both
// the main window and the tray window; the preload reads them here and
// constructs the transport.
//
// IPC is used only as a one-way bridge for Electron-local events that
// the main process generates from native keyboard intercepts
// (terminal:zoom, shortcut:forward, app:navigate) and for shell-facing
// concerns (shell:openExternal, tray:navigate, shell:reconnect).
// -----------------------------------------------------------------------------

import { createORPCClient } from '@orpc/client'
import { RPCLink } from '@orpc/client/fetch'
import { encodeEnvelope, makeEnvelope, PROTOCOL_VERSION, parseEnvelope } from '@wanda/wire'
import { contextBridge, ipcRenderer } from 'electron'
import { createWandaApi, type WandaAPI } from './preload/api'
import { createWsTransport } from './preload/ws-transport'

// --- Parse transport config from --wanda-* CLI args ------------------------

function parseArg(prefix: string): string | undefined {
  const match = process.argv.find((a) => a.startsWith(prefix))
  return match ? match.slice(prefix.length) : undefined
}

const httpUrl = parseArg('--wanda-http-url=')
const wsUrl = parseArg('--wanda-ws-url=')
const token = parseArg('--wanda-token=')
if (!httpUrl || !wsUrl || !token) {
  throw new Error('Wanda preload requires --wanda-http-url, --wanda-ws-url, and --wanda-token additionalArguments')
}

const transport = createWsTransport({
  httpUrl,
  wsUrl,
  sessionToken: token,
  platform: 'electron',
  platformSend: (channel, ...args) => {
    ipcRenderer.send(channel, ...args)
  },
  // Request/response IPC for main-process-only APIs (ServerRegistry).
  platformInvoke: (channel, ...args) => ipcRenderer.invoke(channel, ...args),
})

// Bridge Electron-local channels (generated by main.ts from native
// keyboard intercepts) into the WS transport's listener registry so
// `window.wanda.terminal.onZoom` / `.shortcut.onForward` / `.app.onNavigate`
// still fire even though these events never travel over the WebSocket.
const ELECTRON_LOCAL_CHANNELS = ['terminal:zoom', 'shortcut:forward', 'app:navigate', 'shell:reconnect'] as const

for (const channel of ELECTRON_LOCAL_CHANNELS) {
  ipcRenderer.on(channel, (_event, ...args) => {
    transport.dispatch(channel, ...args)
  })
}

const api = createWandaApi(transport)

// Re-export the type so existing `import type { WandaAPI } from '../../electron/preload'`
// imports keep working.
export type { WandaAPI }

contextBridge.exposeInMainWorld('wanda', api)

// E2E-only helper bridge. Playwright `evaluate()` runs in the renderer
// context where bare `import('@orpc/client')` can't resolve (Vite bundled
// the module non-dynamically), so we expose a small helper that builds an
// oRPC RPCLink in the preload process — which DOES have the module — and
// uses it to make RPC calls against arbitrary paired servers on behalf of
// the test. Gated behind an env var so it's never exposed in prod.
if (process.env.WANDA_E2E_EXPOSE_TEST_HELPERS === '1') {
  type AnyRpcClient = Record<string, Record<string, (input: unknown) => Promise<unknown>>>

  const pairedClient = async (opts: { baseUrl: string; token: string; path: string[]; input: unknown }) => {
    const link = new RPCLink({
      url: opts.baseUrl,
      headers: () => ({ authorization: `Bearer ${opts.token}` }),
    })
    const client = createORPCClient<AnyRpcClient>(link) as unknown as Record<string, unknown>
    let cursor: unknown = client
    for (const segment of opts.path) {
      if (cursor == null || (typeof cursor !== 'object' && typeof cursor !== 'function')) {
        throw new Error(`oRPC path ${opts.path.join('.')} unreachable`)
      }
      cursor = (cursor as Record<string, unknown>)[segment]
    }
    if (typeof cursor !== 'function') throw new Error(`oRPC path ${opts.path.join('.')} not callable`)
    return await (cursor as (input: unknown) => Promise<unknown>)(opts.input)
  }

  // -------------------------------------------------------------------------
  // Paired-terminal bridge for E2E. Opens a WS to the paired server's
  // /events channel with a one-shot wsToken and buffers all terminal:data
  // envelopes the server pushes for the specified ptyInstanceId. The test
  // can then pull the buffered data, write input, and dispose — which is
  // exactly what the production PairedTerminalBridge does, but exposed
  // as a cross-context-bridge-safe handle (serializable string values).
  // -------------------------------------------------------------------------
  interface TerminalSessionHandle {
    id: string
  }
  interface PairedBridgeSession {
    ws: WebSocket
    buffer: string
    subs: Map<string, string>
    exitCodes: Map<string, number>
  }
  const bridgeSessions = new Map<string, PairedBridgeSession>()
  let nextBridgeId = 0

  function randHex(): string {
    return String(++nextBridgeId) + '-' + Math.random().toString(36).slice(2, 10)
  }

  const openPairedTerminal = async (opts: {
    baseUrl: string
    wsToken: string
    ptyInstanceId: string
  }): Promise<TerminalSessionHandle> => {
    const wsUrl = opts.baseUrl.replace(/^http/, 'ws') + '/events?wsToken=' + encodeURIComponent(opts.wsToken)
    const ws = new WebSocket(wsUrl)
    await new Promise<void>((resolve, reject) => {
      const t = setTimeout(() => reject(new Error('ws open timeout')), 10_000)
      ws.addEventListener(
        'open',
        () => {
          clearTimeout(t)
          resolve()
        },
        { once: true },
      )
      ws.addEventListener(
        'error',
        () => {
          clearTimeout(t)
          reject(new Error('ws error'))
        },
        { once: true },
      )
    })
    // New-world protocol: send sys:hello and wait for sys:hello-ack before
    // treating the socket as ready.
    ws.send(encodeEnvelope(makeEnvelope('sys:hello', [{ v: PROTOCOL_VERSION, clientId: 'wanda-e2e-bridge' }])))
    await new Promise<void>((resolve, reject) => {
      const t = setTimeout(() => reject(new Error('hello-ack timeout')), 10_000)
      const onAck = (event: MessageEvent): void => {
        const data = typeof event.data === 'string' ? event.data : String(event.data)
        const env = parseEnvelope(data)
        if (!env) return
        if (env.channel === 'sys:hello-ack') {
          clearTimeout(t)
          ws.removeEventListener('message', onAck)
          resolve()
        } else if (env.channel === 'sys:hello-rejected') {
          clearTimeout(t)
          ws.removeEventListener('message', onAck)
          reject(new Error('hello-rejected'))
        }
      }
      ws.addEventListener('message', onAck)
    })
    const session: PairedBridgeSession = { ws, buffer: '', subs: new Map(), exitCodes: new Map() }
    session.subs.set(opts.ptyInstanceId, '')

    ws.addEventListener('message', (event) => {
      const data = typeof event.data === 'string' ? event.data : String(event.data)
      const env = parseEnvelope(data)
      if (!env) return
      if (env.channel === 'terminal:data') {
        const [termId, data] = env.args as [string, string]
        if (session.subs.has(termId)) {
          const prev = session.subs.get(termId) ?? ''
          session.subs.set(termId, prev + data)
        }
      } else if (env.channel === 'terminal:exit') {
        const [termId, code] = env.args as [string, number]
        session.exitCodes.set(termId, code)
      }
    })

    const id = randHex()
    bridgeSessions.set(id, session)
    return { id }
  }

  const pairedTerminalWrite = (handle: TerminalSessionHandle, ptyInstanceId: string, data: string) => {
    const session = bridgeSessions.get(handle.id)
    if (!session) throw new Error('bridge session not found')
    if (session.ws.readyState !== session.ws.OPEN) throw new Error('bridge ws not open')
    session.ws.send(encodeEnvelope(makeEnvelope('terminal:write', [ptyInstanceId, data])))
  }

  const pairedTerminalResize = (handle: TerminalSessionHandle, ptyInstanceId: string, cols: number, rows: number) => {
    const session = bridgeSessions.get(handle.id)
    if (!session) throw new Error('bridge session not found')
    if (session.ws.readyState !== session.ws.OPEN) throw new Error('bridge ws not open')
    session.ws.send(encodeEnvelope(makeEnvelope('terminal:resize', [ptyInstanceId, cols, rows])))
  }

  const pairedTerminalRead = (handle: TerminalSessionHandle, ptyInstanceId: string): string => {
    const session = bridgeSessions.get(handle.id)
    if (!session) throw new Error('bridge session not found')
    return session.subs.get(ptyInstanceId) ?? ''
  }

  const pairedTerminalClose = (handle: TerminalSessionHandle) => {
    const session = bridgeSessions.get(handle.id)
    if (!session) return
    try {
      session.ws.close()
    } catch {
      // ws.close() throws only if the socket's already been garbage-
      // collected mid-teardown, which is harmless here.
    }
    bridgeSessions.delete(handle.id)
  }

  contextBridge.exposeInMainWorld('__wandaTestHooks', {
    pairedClient,
    openPairedTerminal,
    pairedTerminalWrite,
    pairedTerminalResize,
    pairedTerminalRead,
    pairedTerminalClose,
  })
}
