import type { DiffLineAnnotation, FileContents } from '@pierre/diffs/react'
import { MultiFileDiff, PatchDiff, Virtualizer } from '@pierre/diffs/react'
import { useQuery } from '@tanstack/react-query'
import { useCallback, useMemo } from 'react'
import { useAutoGeneratedFiles } from '@/features/git/hooks/use-auto-generated'
import { useReviewComments } from '@/features/git/hooks/use-review'
import { useGitDiffStore } from '@/features/git/store/git-diff-store'
import { getCommentsForFile, useReviewStore } from '@/features/git/store/review-store'
import { useViewedFilesStore } from '@/features/git/store/viewed-files-store'
import { type FilePatchInfo, splitAndParsePatch } from '@/features/git/utils/diff-utils'
import type { DiffMode } from '@/features/git/utils/git-status'
import { orpcUtils } from '@/shared/orpc'
import type { ReviewComment, ReviewSide } from '@/types/schema'
import { AutoGeneratedBadge, FileCollapsePrefix, FileViewedToggle } from './file-viewed-toggle'
import { ReviewCommentCard } from './review/comment-card'
import { ReviewCommentForm } from './review/comment-form'

interface DiffViewerProps {
  podId: string
  diffMode: DiffMode
  mergeBase?: string
  diff: string
  untrackedFiles?: string[]
  selectedFile?: string | null
  /** When true, gutter "+" buttons enable inline review commenting and saved
   *  comments render as line annotations. Only meaningful in branch-diff mode. */
  enableComments?: boolean
  className?: string
}

const DIFF_OPTIONS = {
  diffIndicators: 'bars' as const,
  overflow: 'scroll' as const,
  lineDiffType: 'word' as const,
  tokenizeMaxLineLength: 10000,
  maxLineDiffLength: 500,
  disableFileHeader: false,
  expansionLineCount: 20,
}

type ReviewAnnotationMeta =
  | { type: 'comment'; comment: ReviewComment }
  | { type: 'draft'; filePath: string; endLine?: number; anchorContent?: string }

/** Slice of a file (1-indexed lines) that a comment is anchored to. */
function extractAnchorContent(content: string | null | undefined, startLine: number, endLine?: number): string {
  if (!content) return ''
  const lines = content.split('\n')
  const start = Math.max(0, startLine - 1)
  const end = Math.min(lines.length, endLine ?? startLine)
  return lines.slice(start, end).join('\n')
}

function ExpandableFileDiff({
  podId,
  filePatch,
  oldRef,
  newRef,
  theme,
  diffStyle,
  autoGenerated,
  enableComments,
}: {
  podId: string
  filePatch: FilePatchInfo
  oldRef: string | undefined
  newRef: string | undefined
  theme: string
  diffStyle: 'unified' | 'split'
  autoGenerated?: boolean
  enableComments?: boolean
}) {
  const filePath = filePatch.newPath || filePatch.oldPath
  const collapsed = useViewedFilesStore((s) => s.collapsed.has(`${podId}:${filePath}`))

  const { data: oldContent } = useQuery({
    ...orpcUtils.git.getFileContent.queryOptions({
      input: { podId, filePath: filePatch.oldPath, ref: oldRef },
    }),
    staleTime: 30000,
    enabled: !filePatch.isNew && !collapsed,
  })

  const { data: newContent } = useQuery({
    ...orpcUtils.git.getFileContent.queryOptions({
      input: { podId, filePath: filePatch.newPath, ref: newRef },
    }),
    staleTime: 30000,
    enabled: !filePatch.isDeleted && !collapsed,
  })

  const renderHeaderPrefix = useCallback(
    () => <FileCollapsePrefix podId={podId} filePath={filePath} />,
    [podId, filePath],
  )
  const renderHeaderMetadata = useCallback(
    () => (
      <>
        {autoGenerated && <AutoGeneratedBadge />}
        <FileViewedToggle podId={podId} filePath={filePath} />
      </>
    ),
    [podId, filePath, autoGenerated],
  )

  const review = useReviewExtensions({
    enabled: enableComments === true,
    filePath,
    oldContent,
    newContent,
  })

  const options = useMemo(
    () => ({ theme, diffStyle, ...DIFF_OPTIONS, collapsed, ...review.options }),
    [theme, diffStyle, collapsed, review.options],
  )

  // When collapsed we skip the file-content queries entirely — render the
  // header-only PatchDiff view so users can still expand on demand.
  if (collapsed) {
    return (
      <PatchDiff
        patch={filePatch.patch}
        options={options}
        lineAnnotations={review.lineAnnotations}
        renderAnnotation={review.renderAnnotation}
        renderHeaderPrefix={renderHeaderPrefix}
        renderHeaderMetadata={renderHeaderMetadata}
      />
    )
  }

  // undefined = still loading, null/string = resolved
  const oldReady = filePatch.isNew || oldContent !== undefined
  const newReady = filePatch.isDeleted || newContent !== undefined

  if (oldReady && newReady) {
    const oldFile: FileContents = { name: filePatch.oldPath, contents: (filePatch.isNew ? '' : oldContent) ?? '' }
    const newFile: FileContents = { name: filePatch.newPath, contents: (filePatch.isDeleted ? '' : newContent) ?? '' }
    return (
      <MultiFileDiff
        oldFile={oldFile}
        newFile={newFile}
        options={options}
        lineAnnotations={review.lineAnnotations}
        renderAnnotation={review.renderAnnotation}
        renderHeaderPrefix={renderHeaderPrefix}
        renderHeaderMetadata={renderHeaderMetadata}
      />
    )
  }

  return (
    <PatchDiff
      patch={filePatch.patch}
      options={options}
      lineAnnotations={review.lineAnnotations}
      renderAnnotation={review.renderAnnotation}
      renderHeaderPrefix={renderHeaderPrefix}
      renderHeaderMetadata={renderHeaderMetadata}
    />
  )
}

function UntrackedFileDiff({
  podId,
  filePath,
  theme,
  diffStyle,
  autoGenerated,
  enableComments,
}: {
  podId: string
  filePath: string
  theme: string
  diffStyle: 'unified' | 'split'
  autoGenerated?: boolean
  enableComments?: boolean
}) {
  const collapsed = useViewedFilesStore((s) => s.collapsed.has(`${podId}:${filePath}`))

  const { data: content, isLoading } = useQuery({
    ...orpcUtils.git.getFileContent.queryOptions({
      input: { podId, filePath, ref: undefined },
    }),
    staleTime: 5000,
    enabled: !collapsed,
  })

  const renderHeaderPrefix = useCallback(
    () => <FileCollapsePrefix podId={podId} filePath={filePath} />,
    [podId, filePath],
  )
  const renderHeaderMetadata = useCallback(
    () => (
      <>
        {autoGenerated && <AutoGeneratedBadge />}
        <FileViewedToggle podId={podId} filePath={filePath} />
      </>
    ),
    [podId, filePath, autoGenerated],
  )

  // For untracked files there's no "old" content — the additions side carries
  // the new file, and the deletions side is empty.
  const review = useReviewExtensions({
    enabled: enableComments === true,
    filePath,
    oldContent: '',
    newContent: content,
  })

  const options = useMemo(
    () => ({ theme, diffStyle, ...DIFF_OPTIONS, collapsed, ...review.options }),
    [theme, diffStyle, collapsed, review.options],
  )

  const safeContent = content ?? ''
  const oldFile: FileContents = { name: filePath, contents: '' }
  const newFile: FileContents = { name: filePath, contents: safeContent }

  if (!collapsed && isLoading) {
    return <div className="flex items-center justify-center h-32 text-zinc-500 text-xs">Loading...</div>
  }

  return (
    <MultiFileDiff
      oldFile={oldFile}
      newFile={newFile}
      options={options}
      lineAnnotations={review.lineAnnotations}
      renderAnnotation={review.renderAnnotation}
      renderHeaderPrefix={renderHeaderPrefix}
      renderHeaderMetadata={renderHeaderMetadata}
    />
  )
}

/**
 * Adds gutter-click commenting and renders saved comments as line annotations.
 * Returns no-op values when `enabled === false` so the diff renders cleanly
 * without commenting affordances.
 */
function useReviewExtensions({
  enabled,
  filePath,
  oldContent,
  newContent,
}: {
  enabled: boolean
  filePath: string
  oldContent: string | null | undefined
  newContent: string | null | undefined
}): {
  lineAnnotations: DiffLineAnnotation<ReviewAnnotationMeta>[] | undefined
  renderAnnotation: ((annotation: DiffLineAnnotation<ReviewAnnotationMeta>) => React.ReactNode) | undefined
  options: {
    enableGutterUtility?: boolean
    enableLineSelection?: boolean
    onGutterUtilityClick?: (range: {
      start: number
      end: number
      side?: 'deletions' | 'additions'
      endSide?: 'deletions' | 'additions'
    }) => void
  }
} {
  const activeReviewId = useReviewStore((s) => s.activeReviewId)
  const draftAnchor = useReviewStore((s) => s.draftAnchor)
  const setDraftAnchor = useReviewStore((s) => s.setDraftAnchor)
  // Hook is called unconditionally; gating happens via `enabled` on the query
  // inside useReviewComments (it skips when reviewId is empty/null).
  const { comments } = useReviewComments(enabled ? activeReviewId : null)

  const fileComments = useMemo(
    () => (enabled ? getCommentsForFile(comments, filePath) : []),
    [enabled, comments, filePath],
  )

  const lineAnnotations = useMemo(() => {
    if (!enabled) return undefined
    const annotations: DiffLineAnnotation<ReviewAnnotationMeta>[] = []
    for (const comment of fileComments) {
      annotations.push({
        side: comment.side,
        lineNumber: comment.startLine,
        metadata: { type: 'comment', comment },
      })
    }
    if (draftAnchor && draftAnchor.filePath === filePath) {
      annotations.push({
        side: draftAnchor.side,
        lineNumber: draftAnchor.startLine,
        metadata: {
          type: 'draft',
          filePath,
          endLine: draftAnchor.endLine,
          anchorContent: draftAnchor.anchorContent,
        },
      })
    }
    return annotations
  }, [enabled, fileComments, draftAnchor, filePath])

  const renderAnnotation = useCallback(
    (annotation: DiffLineAnnotation<ReviewAnnotationMeta>) => {
      if (!annotation.metadata) return null
      if (annotation.metadata.type === 'comment') {
        return <ReviewCommentCard comment={annotation.metadata.comment} />
      }
      return (
        <ReviewCommentForm
          filePath={filePath}
          side={annotation.side}
          startLine={annotation.lineNumber}
          endLine={annotation.metadata.endLine}
          anchorContent={annotation.metadata.anchorContent}
        />
      )
    },
    [filePath],
  )

  const handleGutterClick = useCallback(
    (range: { start: number; side?: 'deletions' | 'additions'; end: number; endSide?: 'deletions' | 'additions' }) => {
      const side: ReviewSide = range.side ?? 'additions'
      const endLine = range.end !== range.start ? range.end : undefined
      const source = side === 'deletions' ? oldContent : newContent
      const anchorContent = extractAnchorContent(source, range.start, endLine)
      setDraftAnchor({
        filePath,
        side,
        startLine: range.start,
        endLine,
        anchorContent,
      })
    },
    [setDraftAnchor, filePath, oldContent, newContent],
  )

  if (!enabled) {
    return { lineAnnotations: undefined, renderAnnotation: undefined, options: {} }
  }

  return {
    lineAnnotations,
    renderAnnotation,
    options: {
      enableGutterUtility: true,
      enableLineSelection: true,
      onGutterUtilityClick: handleGutterClick,
    },
  }
}

export function DiffViewer({
  podId,
  diffMode,
  mergeBase,
  diff,
  untrackedFiles,
  selectedFile,
  enableComments,
  className,
}: DiffViewerProps) {
  const theme = useGitDiffStore((s) => s.theme)
  const diffStyle = useGitDiffStore((s) => s.diffStyle)
  const fontSize = useGitDiffStore((s) => s.fontSize)

  const oldRef = diffMode === 'uncommitted' ? 'HEAD' : mergeBase
  const newRef = diffMode === 'uncommitted' ? undefined : 'HEAD'

  const filePatches = useMemo(() => {
    const all = splitAndParsePatch(diff)
    if (!selectedFile) return all
    return all.filter((fp) => fp.newPath === selectedFile || fp.oldPath === selectedFile)
  }, [diff, selectedFile])

  const untrackedToRender = useMemo(() => {
    const all = untrackedFiles ?? []
    if (!selectedFile) return all
    return all.filter((p) => p === selectedFile)
  }, [untrackedFiles, selectedFile])

  const allPathsForAutogen = useMemo(() => {
    const paths: string[] = []
    for (const fp of filePatches) paths.push(fp.newPath || fp.oldPath)
    for (const p of untrackedToRender) paths.push(p)
    return paths
  }, [filePatches, untrackedToRender])
  const { isAutoGenerated } = useAutoGeneratedFiles(podId, allPathsForAutogen)

  if (filePatches.length === 0 && untrackedToRender.length === 0) {
    return <div className="flex items-center justify-center h-full text-zinc-500 text-xs">No changes</div>
  }

  let sep = 0

  return (
    <Virtualizer
      className={className}
      style={
        {
          position: 'absolute',
          inset: 0,
          overflow: 'auto',
          '--diffs-font-size': `${fontSize}px`,
          '--diffs-line-height': `${Math.round(fontSize * 1.54)}px`,
        } as React.CSSProperties
      }
    >
      {filePatches.map((fp) => {
        const showSep = sep++ > 0
        const path = fp.newPath || fp.oldPath
        return (
          <div key={`p:${path}`}>
            {showSep && <div className="h-2 bg-zinc-950 border-y border-zinc-700/60" />}
            <ExpandableFileDiff
              podId={podId}
              filePatch={fp}
              oldRef={oldRef}
              newRef={newRef}
              theme={theme}
              diffStyle={diffStyle}
              autoGenerated={isAutoGenerated(path)}
              enableComments={enableComments}
            />
          </div>
        )
      })}
      {untrackedToRender.map((path) => {
        const showSep = sep++ > 0
        return (
          <div key={`u:${path}`}>
            {showSep && <div className="h-2 bg-zinc-950 border-y border-zinc-700/60" />}
            <UntrackedFileDiff
              podId={podId}
              filePath={path}
              theme={theme}
              diffStyle={diffStyle}
              autoGenerated={isAutoGenerated(path)}
              enableComments={enableComments}
            />
          </div>
        )
      })}
    </Virtualizer>
  )
}
