import { useToggleFileViewed } from '@/features/git/hooks/use-file-viewed'
import { useViewedFilesStore } from '@/features/git/store/viewed-files-store'
import { RiArrowDownSLine, RiCheckboxBlankCircleLine, RiCheckboxCircleFill } from '@/lib/icons'
import { Button } from '@/ui/button'

/** Small pill shown in a file header when the file matches an auto-generated glob. */
export function AutoGeneratedBadge() {
  return (
    <span
      className="text-[9px] font-medium text-zinc-500 bg-zinc-800 border border-zinc-700/60 px-1.5 py-px rounded uppercase tracking-wider"
      title="Auto-generated file (collapsed by default)"
    >
      auto-generated
    </span>
  )
}

interface FileViewedToggleProps {
  podId: string
  filePath: string
}

/**
 * "Viewed" button rendered via @pierre/diffs `renderHeaderMetadata`.
 * Marking a file viewed also collapses it (matches GitHub's PR review UX).
 * Persisted against a content hash — drifted files automatically unmark.
 */
export function FileViewedToggle({ podId, filePath }: FileViewedToggleProps) {
  const viewed = useViewedFilesStore((s) => s.viewed.has(`${podId}:${filePath}`))
  const toggleViewed = useToggleFileViewed(podId)

  return (
    <Button
      variant={viewed ? 'secondary' : 'ghost'}
      size="xs"
      onClick={(e) => {
        e.stopPropagation()
        toggleViewed(filePath)
      }}
      title={viewed ? 'Mark as not viewed' : 'Mark as viewed'}
      className={viewed ? 'text-emerald-400' : ''}
    >
      {viewed ? <RiCheckboxCircleFill className="text-emerald-400" /> : <RiCheckboxBlankCircleLine />}
      Viewed
    </Button>
  )
}

interface FileCollapsePrefixProps {
  podId: string
  filePath: string
}

/**
 * Chevron toggle rendered via @pierre/diffs `renderHeaderPrefix` (before the
 * filename). Toggles the file's collapsed state independently of viewed.
 */
export function FileCollapsePrefix({ podId, filePath }: FileCollapsePrefixProps) {
  const collapsed = useViewedFilesStore((s) => s.collapsed.has(`${podId}:${filePath}`))
  const toggleCollapsed = useViewedFilesStore((s) => s.toggleCollapsed)

  return (
    <Button
      variant="ghost"
      size="icon-xs"
      onClick={(e) => {
        e.stopPropagation()
        toggleCollapsed(podId, filePath)
      }}
      title={collapsed ? 'Expand file' : 'Collapse file'}
      aria-pressed={collapsed}
    >
      <RiArrowDownSLine className={`transition-transform ${collapsed ? '-rotate-90' : ''}`} />
    </Button>
  )
}
