import { Checkbox } from '@/ui/checkbox'
import { ToggleGroup, ToggleGroupItem } from '@/ui/toggle-group'
import { useSettingsFormContext } from './context'
import { BrowseField, Field, FieldHint, FieldLabel, SectionHeading, TextField } from './fields'

const LOCATION_HINTS: Record<string, string> = {
  'app-default': 'Uses the global default worktrees directory.',
  alongside: 'Creates worktrees next to the repo directory.',
  custom: 'Uses a custom directory for this workspace.',
}

function WorktreeOptions() {
  const { state, set, handleBrowseWorktreeBaseDir } = useSettingsFormContext()
  return (
    <div className="flex flex-col gap-3 pl-5 border-l-2 border-zinc-800">
      <label className="flex items-center gap-2 cursor-pointer">
        <Checkbox checked={state.gitWorktreeCopyHidden} onCheckedChange={(v) => set({ gitWorktreeCopyHidden: !!v })} />
        <span className="text-xs text-zinc-300">Copy hidden files (.env, etc.)</span>
      </label>

      <TextField
        label="Branch from"
        value={state.branchFrom}
        onChange={(branchFrom) => set({ branchFrom })}
        placeholder="e.g. origin/main"
        mono
      />

      <TextField
        label="Remote origin"
        value={state.remoteOrigin}
        onChange={(remoteOrigin) => set({ remoteOrigin })}
        placeholder="e.g. origin"
        mono
      />

      <Field label="Pod worktree location" hint={LOCATION_HINTS[state.worktreeLocationMode]}>
        <ToggleGroup
          value={[state.worktreeLocationMode]}
          onValueChange={(value) => {
            if (value.length) set({ worktreeLocationMode: value[0] })
          }}
          variant="outline"
          size="sm"
        >
          <ToggleGroupItem value="app-default">App default</ToggleGroupItem>
          <ToggleGroupItem value="alongside">Alongside</ToggleGroupItem>
          <ToggleGroupItem value="custom">Custom</ToggleGroupItem>
        </ToggleGroup>
      </Field>

      {state.worktreeLocationMode === 'custom' && (
        <BrowseField
          label="Custom worktree directory"
          value={state.worktreeBaseDir}
          onChange={(worktreeBaseDir) => set({ worktreeBaseDir })}
          onBrowse={handleBrowseWorktreeBaseDir}
          placeholder="/path/to/worktrees"
        />
      )}
    </div>
  )
}

function AutoGeneratedGlobs() {
  const { state, set } = useSettingsFormContext()
  const globs = state.autoGeneratedGlobs
  return (
    <div className="flex flex-col gap-1 pt-2">
      <div className="flex items-center justify-between">
        <FieldLabel>Auto-generated file globs</FieldLabel>
        {globs != null && (
          <button
            type="button"
            onClick={() => set({ autoGeneratedGlobs: null })}
            className="text-[10px] text-zinc-500 hover:text-zinc-300"
          >
            Reset to defaults
          </button>
        )}
      </div>
      {globs == null ? (
        <button
          type="button"
          onClick={() => set({ autoGeneratedGlobs: '**/*.gen.*' })}
          className="text-left h-7 rounded-md border border-dashed border-zinc-700 bg-zinc-900 px-2 text-xs text-zinc-500 hover:text-zinc-300 hover:border-zinc-600"
        >
          Using defaults (**/*.gen.*). Click to customize.
        </button>
      ) : (
        <textarea
          value={globs}
          onChange={(e) => set({ autoGeneratedGlobs: e.target.value })}
          placeholder="**/*.gen.*&#10;**/*.pb.go&#10;dist/**"
          rows={3}
          className="rounded-md border border-zinc-700 bg-zinc-800 px-2 py-1.5 text-xs text-zinc-200 placeholder:text-zinc-600 outline-none focus:border-zinc-500 font-mono resize-none"
        />
      )}
      <FieldHint>
        One glob per line. Matching files are collapsed by default in the diff/review views with an
        &ldquo;auto-generated&rdquo; tag. Patterns from <code>.gitattributes</code> (
        <code>linguist-generated=true</code>) are also included automatically.
      </FieldHint>
    </div>
  )
}

export function GitSection() {
  const { state, set } = useSettingsFormContext()
  return (
    <section>
      <SectionHeading>Git &amp; Worktrees</SectionHeading>
      <div className="flex flex-col gap-3">
        <label className="flex items-center gap-2 cursor-pointer">
          <Checkbox checked={state.gitWorktreeEnabled} onCheckedChange={(v) => set({ gitWorktreeEnabled: !!v })} />
          <span className="text-xs text-zinc-300">Create git worktree for new pods</span>
        </label>

        {state.gitWorktreeEnabled && <WorktreeOptions />}

        <AutoGeneratedGlobs />
      </div>
    </section>
  )
}
