import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useCallback, useEffect, useMemo, useReducer, useState } from 'react'
import { toast } from 'sonner'
import { orpcUtils } from '@/shared/orpc'
import type {
  GraphiteBranchDefault,
  GraphiteCommitDefault,
  GraphitePullDefault,
  GraphitePushDefault,
} from '../graphite-section'

export type SourceMode = 'directory' | 'clone' | 'worktree'
export type WandaMcpPolicy = 'inherit' | 'include' | 'exclude'

interface SettingsFormState {
  name: string
  nameManuallySet: boolean
  cwd: string
  sourceMode: SourceMode
  cloneUrl: string
  cloneParentDir: string
  worktreeRepoPath: string
  worktreeBranch: string
  worktreeParentDir: string
  branches: { name: string; current: boolean }[]
  gitWorktreeEnabled: boolean
  gitWorktreeCopyHidden: boolean
  worktreeLocationMode: string
  worktreeBaseDir: string
  branchFrom: string
  remoteOrigin: string
  // `null` = not customized (use defaults + .gitattributes only)
  autoGeneratedGlobs: string | null
  defaultTemplatePodId: string
  defaultWorkenvTemplateId: string
  autoGeneratePodName: boolean
  wandaMcpPolicy: WandaMcpPolicy
  graphiteEnabled: boolean
  graphiteCommit: GraphiteCommitDefault
  graphitePush: GraphitePushDefault
  graphitePull: GraphitePullDefault
  graphiteBranch: GraphiteBranchDefault
  scriptSetup: string
  scriptRun: string
  scriptArchive: string
}

const initialState: SettingsFormState = {
  name: '',
  nameManuallySet: false,
  cwd: '',
  sourceMode: 'directory',
  cloneUrl: '',
  cloneParentDir: '',
  worktreeRepoPath: '',
  worktreeBranch: '',
  worktreeParentDir: '',
  branches: [],
  gitWorktreeEnabled: false,
  gitWorktreeCopyHidden: false,
  worktreeLocationMode: 'app-default',
  worktreeBaseDir: '',
  branchFrom: '',
  remoteOrigin: '',
  autoGeneratedGlobs: null,
  defaultTemplatePodId: '',
  defaultWorkenvTemplateId: '',
  autoGeneratePodName: false,
  wandaMcpPolicy: 'inherit',
  graphiteEnabled: false,
  graphiteCommit: 'modify',
  graphitePush: 'submitStack',
  graphitePull: 'sync',
  graphiteBranch: 'create',
  scriptSetup: '',
  scriptRun: '',
  scriptArchive: '',
}

type Patch = Partial<SettingsFormState>

function reducer(state: SettingsFormState, patch: Patch): SettingsFormState {
  return { ...state, ...patch }
}

function extractRepoName(url: string): string {
  const match = url.match(/\/([^/]+?)(\.git)?$/) || url.match(/:([^/]+?)(\.git)?$/)
  return match?.[1] ?? 'repo'
}

function branchToDirName(branch: string): string {
  return branch.replace(/\//g, '-')
}

interface UseSettingsFormArgs {
  mode: 'create' | 'edit'
  workspaceId?: string
  open: boolean
  onOpenChange: (open: boolean) => void
  onCreated?: () => void
}

export function useSettingsForm({ mode, workspaceId, open, onOpenChange, onCreated }: UseSettingsFormArgs) {
  const queryClient = useQueryClient()
  const isEdit = mode === 'edit' && !!workspaceId

  const { data: workspace } = useQuery({
    ...orpcUtils.workspace.getById.queryOptions({ input: { id: workspaceId ?? '' } }),
    enabled: isEdit && open,
  })

  const { data: wsSettings } = useQuery({
    ...orpcUtils.workspaceSettings.getByWorkspace.queryOptions({ input: { workspaceId: workspaceId ?? '' } }),
    enabled: isEdit && open,
  })

  const [state, set] = useReducer(reducer, initialState)
  const [loading, setLoading] = useState(false)
  const [errors, setErrors] = useState<Record<string, string>>({})

  useEffect(() => {
    if (workspace) {
      set({ name: workspace.name, nameManuallySet: true, cwd: workspace.cwd })
    }
  }, [workspace])

  useEffect(() => {
    if (wsSettings) {
      set({
        gitWorktreeEnabled: wsSettings.gitWorktreeEnabled,
        gitWorktreeCopyHidden: wsSettings.gitWorktreeCopyHiddenFiles,
        worktreeLocationMode: wsSettings.worktreeLocationMode ?? 'app-default',
        worktreeBaseDir: wsSettings.worktreeBaseDir ?? '',
        branchFrom: wsSettings.branchFrom ?? '',
        remoteOrigin: wsSettings.remoteOrigin ?? '',
        defaultTemplatePodId: wsSettings.defaultTemplatePodId ?? '',
        defaultWorkenvTemplateId: wsSettings.defaultWorkenvTemplateId ?? '',
        autoGeneratePodName: wsSettings.autoGeneratePodName,
        wandaMcpPolicy: (wsSettings.wandaMcpPolicy ?? 'inherit') as WandaMcpPolicy,
        scriptSetup: wsSettings.scriptSetup ?? '',
        scriptRun: wsSettings.scriptRun ?? '',
        scriptArchive: wsSettings.scriptArchive ?? '',
        autoGeneratedGlobs: wsSettings.autoGeneratedGlobs != null ? wsSettings.autoGeneratedGlobs.join('\n') : null,
        graphiteEnabled: wsSettings.graphiteEnabled,
        graphiteCommit: wsSettings.graphiteDefaultCommit,
        graphitePush: wsSettings.graphiteDefaultPush,
        graphitePull: wsSettings.graphiteDefaultPull,
        graphiteBranch: wsSettings.graphiteDefaultBranch,
      })
    }
  }, [wsSettings])

  useEffect(() => {
    if (open && !isEdit) set({ wandaMcpPolicy: 'inherit' })
  }, [isEdit, open])

  const autoName = useCallback(
    (value: string) => {
      if (!state.nameManuallySet) set({ name: value })
    },
    [state.nameManuallySet],
  )

  const handleNameChange = useCallback((value: string) => {
    set({ name: value, nameManuallySet: value.length > 0 })
  }, [])

  const handleCloneUrlChange = useCallback(
    (value: string) => {
      set({ cloneUrl: value })
      if (value.trim()) autoName(extractRepoName(value))
    },
    [autoName],
  )

  const handleWorktreeBranchChange = useCallback(
    (value: string) => {
      set({ worktreeBranch: value })
      if (value && state.worktreeRepoPath) {
        const repoName = state.worktreeRepoPath.split('/').filter(Boolean).pop() ?? 'repo'
        autoName(`${repoName}/${value}`)
      }
    },
    [autoName, state.worktreeRepoPath],
  )

  const fetchBranches = useCallback(async (repoPath: string) => {
    try {
      const result = await orpcUtils.app.gitListLocalBranches.call({ repoPath })
      set({ branches: result })
    } catch {
      set({ branches: [] })
    }
  }, [])

  const browse = useCallback(async () => orpcUtils.app.selectDirectory.call({}), [])

  const handleBrowseCwd = useCallback(async () => {
    const dir = await browse()
    if (dir) set({ cwd: dir })
  }, [browse])

  const handleBrowseCloneDir = useCallback(async () => {
    const dir = await browse()
    if (dir) set({ cloneParentDir: dir })
  }, [browse])

  const handleBrowseWorktreeRepo = useCallback(async () => {
    const dir = await browse()
    if (dir) {
      set({ worktreeRepoPath: dir })
      fetchBranches(dir)
    }
  }, [browse, fetchBranches])

  const handleBrowseWorktreeDir = useCallback(async () => {
    const dir = await browse()
    if (dir) set({ worktreeParentDir: dir })
  }, [browse])

  const handleBrowseWorktreeBaseDir = useCallback(async () => {
    const dir = await browse()
    if (dir) set({ worktreeBaseDir: dir })
  }, [browse])

  function validate(): boolean {
    const next: Record<string, string> = {}
    if (!state.name.trim()) next.name = 'Name is required'

    if (isEdit || state.sourceMode === 'directory') {
      if (!state.cwd.trim()) next.cwd = 'Working directory is required'
    } else if (state.sourceMode === 'clone') {
      if (!state.cloneUrl.trim()) next.cloneUrl = 'Repository URL is required'
      if (!state.cloneParentDir.trim()) next.cloneParentDir = 'Destination directory is required'
    } else if (state.sourceMode === 'worktree') {
      if (!state.worktreeRepoPath.trim()) next.worktreeRepoPath = 'Repository path is required'
      if (!state.worktreeBranch) next.worktreeBranch = 'Branch is required'
      if (!state.worktreeParentDir.trim()) next.worktreeParentDir = 'Worktree location is required'
    }

    setErrors(next)
    return Object.keys(next).length === 0
  }

  function invalidate() {
    queryClient.invalidateQueries({ queryKey: orpcUtils.workspace.list.key() })
    if (workspaceId) {
      queryClient.invalidateQueries({
        queryKey: orpcUtils.workspaceSettings.getByWorkspace.key({ input: { workspaceId } }),
      })
    }
  }

  function buildSettingsInput(targetWorkspaceId: string) {
    return {
      workspaceId: targetWorkspaceId,
      defaultTemplatePodId: state.defaultTemplatePodId || null,
      defaultWorkenvTemplateId: state.defaultWorkenvTemplateId || null,
      autoGeneratePodName: state.autoGeneratePodName,
      gitWorktreeEnabled: state.gitWorktreeEnabled,
      gitWorktreeCopyHiddenFiles: state.gitWorktreeCopyHidden,
      worktreeLocationMode: (state.worktreeLocationMode as 'app-default' | 'alongside' | 'custom') || null,
      worktreeBaseDir: state.worktreeBaseDir.trim() || null,
      branchFrom: state.branchFrom.trim() || null,
      remoteOrigin: state.remoteOrigin.trim() || null,
      scriptSetup: state.scriptSetup.trim() || null,
      scriptRun: state.scriptRun.trim() || null,
      scriptArchive: state.scriptArchive.trim() || null,
      autoGeneratedGlobs:
        state.autoGeneratedGlobs == null
          ? null
          : state.autoGeneratedGlobs
              .split('\n')
              .map((s) => s.trim())
              .filter(Boolean),
      wandaMcpPolicy: state.wandaMcpPolicy,
      graphiteEnabled: state.graphiteEnabled,
      graphiteDefaultCommit: state.graphiteCommit,
      graphiteDefaultPush: state.graphitePush,
      graphiteDefaultPull: state.graphitePull,
      graphiteDefaultBranch: state.graphiteBranch,
    }
  }

  async function handleSave() {
    if (!validate()) return

    setLoading(true)
    try {
      if (isEdit) {
        await orpcUtils.workspace.update.call({ id: workspaceId!, name: state.name.trim(), cwd: state.cwd })
        await orpcUtils.workspaceSettings.update.call(buildSettingsInput(workspaceId!))
        invalidate()
        onOpenChange(false)
      } else {
        let resolvedCwd = ''
        let repoPath: string | undefined

        if (state.sourceMode === 'directory') {
          resolvedCwd = state.cwd.trim()
        } else if (state.sourceMode === 'clone') {
          const repoName = extractRepoName(state.cloneUrl)
          const dir = `${state.cloneParentDir.replace(/\/+$/, '')}/${repoName}`
          await orpcUtils.app.gitClone.call({ url: state.cloneUrl.trim(), directory: dir })
          resolvedCwd = dir
          repoPath = dir
        } else if (state.sourceMode === 'worktree') {
          const dirName = branchToDirName(state.worktreeBranch)
          const dir = `${state.worktreeParentDir.replace(/\/+$/, '')}/${dirName}`
          await orpcUtils.app.gitWorktreeAdd.call({
            repoPath: state.worktreeRepoPath,
            branch: state.worktreeBranch,
            directory: dir,
          })
          resolvedCwd = dir
          repoPath = state.worktreeRepoPath
        }

        const newWorkspace = await orpcUtils.workspace.create.call({
          name: state.name.trim(),
          cwd: resolvedCwd,
          repoPath,
        })

        const hasSettings =
          state.defaultTemplatePodId ||
          state.defaultWorkenvTemplateId ||
          state.autoGeneratePodName ||
          state.gitWorktreeEnabled ||
          state.branchFrom.trim() ||
          state.remoteOrigin.trim() ||
          state.scriptSetup.trim() ||
          state.scriptRun.trim() ||
          state.scriptArchive.trim() ||
          state.graphiteEnabled ||
          state.wandaMcpPolicy !== 'inherit'
        if (hasSettings) {
          await orpcUtils.workspaceSettings.update.call(buildSettingsInput(newWorkspace.id))
        }

        invalidate()
        onCreated?.()
        onOpenChange(false)
      }
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Operation failed')
    } finally {
      setLoading(false)
    }
  }

  const effectiveSourceMode = isEdit ? 'directory' : state.sourceMode

  const cloneTargetPath = useMemo(
    () =>
      state.cloneUrl && state.cloneParentDir
        ? `${state.cloneParentDir.replace(/\/+$/, '')}/${extractRepoName(state.cloneUrl)}`
        : null,
    [state.cloneUrl, state.cloneParentDir],
  )

  const worktreeTargetPath = useMemo(
    () =>
      state.worktreeBranch && state.worktreeParentDir
        ? `${state.worktreeParentDir.replace(/\/+$/, '')}/${branchToDirName(state.worktreeBranch)}`
        : null,
    [state.worktreeBranch, state.worktreeParentDir],
  )

  const graphiteRepoPath = isEdit
    ? (workspace?.repoPath ?? state.cwd.trim()) || null
    : state.sourceMode === 'worktree'
      ? state.worktreeRepoPath.trim() || null
      : state.sourceMode === 'clone'
        ? cloneTargetPath
        : state.cwd.trim() || null

  const buttonText = loading
    ? state.sourceMode === 'clone'
      ? 'Cloning...'
      : state.sourceMode === 'worktree'
        ? 'Creating worktree...'
        : 'Saving...'
    : isEdit
      ? 'Save'
      : 'Create'

  return {
    isEdit,
    workspace,
    state,
    set,
    errors,
    loading,
    handleNameChange,
    handleCloneUrlChange,
    handleWorktreeBranchChange,
    fetchBranches,
    handleBrowseCwd,
    handleBrowseCloneDir,
    handleBrowseWorktreeRepo,
    handleBrowseWorktreeDir,
    handleBrowseWorktreeBaseDir,
    handleSave,
    effectiveSourceMode,
    cloneTargetPath,
    worktreeTargetPath,
    graphiteRepoPath,
    buttonText,
  }
}

export type SettingsFormApi = ReturnType<typeof useSettingsForm>
