import { useQuery } from '@tanstack/react-query'
import { useCallback, useEffect } from 'react'
import { useViewedFilesStore } from '@/features/git/store/viewed-files-store'
import { matchesAnyGlob } from '@/features/git/utils/glob-match'
import { orpcUtils } from '@/shared/orpc'

/**
 * Fetches the auto-generated file glob patterns for the given pod's
 * workspace and returns a check function.
 *
 * Also auto-collapses any file in `filePaths` that matches the patterns
 * on first load, unless the user has already explicitly toggled its
 * collapsed state. This prevents auto-gen files from loading their
 * content by default.
 */
export function useAutoGeneratedFiles(podId: string, filePaths: string[]) {
  const setCollapsed = useViewedFilesStore((s) => s.setCollapsed)

  const { data: patterns = [] } = useQuery({
    ...orpcUtils.git.getAutoGeneratedPatterns.queryOptions({ input: { podId } }),
    staleTime: 60_000,
  })

  const isAutoGenerated = useCallback(
    (filePath: string) => (patterns.length > 0 ? matchesAnyGlob(filePath, patterns) : false),
    [patterns],
  )

  // Auto-collapse auto-generated files on first observation. We only set
  // collapsed when the key isn't already in the set — so once the user
  // toggles it open, they stay open until the component unmounts.
  useEffect(() => {
    if (patterns.length === 0) return
    const state = useViewedFilesStore.getState()
    for (const path of filePaths) {
      if (!matchesAnyGlob(path, patterns)) continue
      const key = `${podId}:${path}`
      if (!state.collapsed.has(key)) {
        setCollapsed(podId, path, true)
      }
    }
  }, [patterns, filePaths, podId, setCollapsed])

  return { patterns, isAutoGenerated }
}
