import { and, eq, inArray } from 'drizzle-orm'
import { v4 as uuid } from 'uuid'
import type { AppDatabase } from '../../../db/connection'
import { fileReviewMarkers, workspaceSettings } from '../../../db/schema'

export function toggleFileReviewMarker(
  db: AppDatabase,
  input: {
    podId: string
    filePath: string
    contentHash: string
  },
) {
  const existing = db
    .select()
    .from(fileReviewMarkers)
    .where(and(eq(fileReviewMarkers.podId, input.podId), eq(fileReviewMarkers.filePath, input.filePath)))
    .get()

  if (existing && existing.contentHash === input.contentHash) {
    db.delete(fileReviewMarkers).where(eq(fileReviewMarkers.id, existing.id)).run()
    return false
  }

  if (existing) {
    db.update(fileReviewMarkers)
      .set({ contentHash: input.contentHash, updatedAt: new Date() })
      .where(eq(fileReviewMarkers.id, existing.id))
      .run()
  } else {
    db.insert(fileReviewMarkers)
      .values({
        id: uuid(),
        podId: input.podId,
        filePath: input.filePath,
        contentHash: input.contentHash,
        createdAt: new Date(),
        updatedAt: new Date(),
      })
      .run()
  }

  return true
}

export function listFileReviewMarkers(db: AppDatabase, podId: string, filePaths: string[]) {
  if (filePaths.length === 0) return []
  return db
    .select()
    .from(fileReviewMarkers)
    .where(and(eq(fileReviewMarkers.podId, podId), inArray(fileReviewMarkers.filePath, filePaths)))
    .all()
}

export function getWorkspaceAutoGeneratedGlobs(db: AppDatabase, workspaceId: string) {
  return db.select().from(workspaceSettings).where(eq(workspaceSettings.workspaceId, workspaceId)).get()
    ?.autoGeneratedGlobs
}
