import { eq } from 'drizzle-orm'
import { v4 as uuid } from 'uuid'
import type { AppDatabase } from '../../../db/connection'
import { workspaceSettings } from '../../../db/schema'

export type WorkspaceSettingsRow = typeof workspaceSettings.$inferSelect
export type WorkspaceSettingsUpdateInput = Partial<
  Pick<
    typeof workspaceSettings.$inferInsert,
    | 'defaultTemplatePodId'
    | 'defaultWorkenvTemplateId'
    | 'autoGeneratePodName'
    | 'defaultRuntime'
    | 'gitWorktreeEnabled'
    | 'gitWorktreeCopyHiddenFiles'
    | 'worktreeLocationMode'
    | 'worktreeBaseDir'
    | 'branchFrom'
    | 'remoteOrigin'
    | 'scriptSetup'
    | 'scriptRun'
    | 'scriptArchive'
    | 'autoGeneratedGlobs'
    | 'wandaMcpPolicy'
    | 'graphiteEnabled'
    | 'graphiteDefaultCommit'
    | 'graphiteDefaultPush'
    | 'graphiteDefaultPull'
    | 'graphiteDefaultBranch'
  >
>

export function getSettingsByWorkspace(db: AppDatabase, workspaceId: string) {
  return db.select().from(workspaceSettings).where(eq(workspaceSettings.workspaceId, workspaceId)).get()
}

export function upsertSettings(db: AppDatabase, workspaceId: string, input: WorkspaceSettingsUpdateInput) {
  const existing = db.select().from(workspaceSettings).where(eq(workspaceSettings.workspaceId, workspaceId)).get()

  if (existing) {
    db.update(workspaceSettings)
      .set({ ...input, updatedAt: new Date() })
      .where(eq(workspaceSettings.id, existing.id))
      .run()
    return db.select().from(workspaceSettings).where(eq(workspaceSettings.id, existing.id)).get()!
  }

  const id = uuid()
  db.insert(workspaceSettings)
    .values({
      id,
      workspaceId,
      ...input,
      createdAt: new Date(),
      updatedAt: new Date(),
    })
    .run()
  return db.select().from(workspaceSettings).where(eq(workspaceSettings.id, id)).get()!
}
