/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkenvTemplatesIndexRouteImport } from './routes/workenv-templates.index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as WorkenvTemplatesTemplateIdRouteImport } from './routes/workenv-templates.$templateId'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'
import { Route as PodsPodIdRouteImport } from './routes/pods.$podId'
import { Route as PlansPlanIdRouteImport } from './routes/plans.$planId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkenvTemplatesIndexRoute = WorkenvTemplatesIndexRouteImport.update({
  id: '/workenv-templates/',
  path: '/workenv-templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkenvTemplatesTemplateIdRoute =
  WorkenvTemplatesTemplateIdRouteImport.update({
    id: '/workenv-templates/$templateId',
    path: '/workenv-templates/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const PodsPodIdRoute = PodsPodIdRouteImport.update({
  id: '/pods/$podId',
  path: '/pods/$podId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/machines': typeof MachinesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/pods/$podId': typeof PodsPodIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/workenv-templates/$templateId': typeof WorkenvTemplatesTemplateIdRoute
  '/plans/': typeof PlansIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/workenv-templates/': typeof WorkenvTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/machines': typeof MachinesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/pods/$podId': typeof PodsPodIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/workenv-templates/$templateId': typeof WorkenvTemplatesTemplateIdRoute
  '/plans': typeof PlansIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/workenv-templates': typeof WorkenvTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/machines': typeof MachinesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/pods/$podId': typeof PodsPodIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/workenv-templates/$templateId': typeof WorkenvTemplatesTemplateIdRoute
  '/plans/': typeof PlansIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/workenv-templates/': typeof WorkenvTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/machines'
    | '/settings'
    | '/tasks'
    | '/plans/$planId'
    | '/pods/$podId'
    | '/templates/$templateId'
    | '/workenv-templates/$templateId'
    | '/plans/'
    | '/templates/'
    | '/workenv-templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/machines'
    | '/settings'
    | '/tasks'
    | '/plans/$planId'
    | '/pods/$podId'
    | '/templates/$templateId'
    | '/workenv-templates/$templateId'
    | '/plans'
    | '/templates'
    | '/workenv-templates'
  id:
    | '__root__'
    | '/'
    | '/machines'
    | '/settings'
    | '/tasks'
    | '/plans/$planId'
    | '/pods/$podId'
    | '/templates/$templateId'
    | '/workenv-templates/$templateId'
    | '/plans/'
    | '/templates/'
    | '/workenv-templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MachinesRoute: typeof MachinesRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  PodsPodIdRoute: typeof PodsPodIdRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  WorkenvTemplatesTemplateIdRoute: typeof WorkenvTemplatesTemplateIdRoute
  PlansIndexRoute: typeof PlansIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  WorkenvTemplatesIndexRoute: typeof WorkenvTemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workenv-templates/': {
      id: '/workenv-templates/'
      path: '/workenv-templates'
      fullPath: '/workenv-templates/'
      preLoaderRoute: typeof WorkenvTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workenv-templates/$templateId': {
      id: '/workenv-templates/$templateId'
      path: '/workenv-templates/$templateId'
      fullPath: '/workenv-templates/$templateId'
      preLoaderRoute: typeof WorkenvTemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pods/$podId': {
      id: '/pods/$podId'
      path: '/pods/$podId'
      fullPath: '/pods/$podId'
      preLoaderRoute: typeof PodsPodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MachinesRoute: MachinesRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  PlansPlanIdRoute: PlansPlanIdRoute,
  PodsPodIdRoute: PodsPodIdRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  WorkenvTemplatesTemplateIdRoute: WorkenvTemplatesTemplateIdRoute,
  PlansIndexRoute: PlansIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  WorkenvTemplatesIndexRoute: WorkenvTemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
