import { execFile } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { APP_DOT_DIR, CONTAINER_PREFIX } from '../../app-config'

const WANDA_SSH_DIR = path.join(APP_DOT_DIR, 'ssh')
const KEY_PATH = path.join(WANDA_SSH_DIR, 'id_ed25519')
const PUB_KEY_PATH = `${KEY_PATH}.pub`
const CONFIG_PATH = path.join(WANDA_SSH_DIR, 'config')
const USER_SSH_CONFIG = path.join(os.homedir(), '.ssh', 'config')

/** Ensure the Wanda SSH key pair exists. Creates it if missing. */
export async function ensureAppSshKey(): Promise<string> {
  if (existsSync(KEY_PATH)) return KEY_PATH
  mkdirSync(WANDA_SSH_DIR, { recursive: true, mode: 0o700 })
  await new Promise<void>((resolve, reject) => {
    execFile('ssh-keygen', ['-t', 'ed25519', '-f', KEY_PATH, '-N', '', '-q'], (err) => (err ? reject(err) : resolve()))
  })
  return KEY_PATH
}

/** Read the Wanda public key. Calls ensureAppSshKey first. */
export async function getPublicKey(): Promise<string> {
  await ensureAppSshKey()
  return readFileSync(PUB_KEY_PATH, 'utf-8').trim()
}

interface PodSshEntry {
  podId: string
  port: number
  user: string
  workDir: string
}

/**
 * Add or update a pod's SSH config entry. Ensures the global wildcard block
 * exists and appends the pod-specific Host block.
 */
export function addPodToSshConfig(entry: PodSshEntry): void {
  mkdirSync(WANDA_SSH_DIR, { recursive: true, mode: 0o700 })

  // Remove existing entry for this pod if present
  removePodFromSshConfig(entry.podId)

  // Ensure the config file exists with the wildcard header
  if (!existsSync(CONFIG_PATH)) {
    const header = [
      '# Auto-generated by Wanda — do not edit manually',
      '',
      `Host ${CONTAINER_PREFIX}-*`,
      '  StrictHostKeyChecking no',
      '  UserKnownHostsFile /dev/null',
      `  IdentityFile ${KEY_PATH}`,
      '',
    ].join('\n')
    writeFileSync(CONFIG_PATH, header, { mode: 0o600 })
  }

  // Append pod entry
  const podBlock = [
    '',
    `Host ${CONTAINER_PREFIX}-${entry.podId}`,
    '  HostName localhost',
    `  Port ${entry.port}`,
    `  User ${entry.user}`,
    '',
  ].join('\n')

  const existing = readFileSync(CONFIG_PATH, 'utf-8')
  writeFileSync(CONFIG_PATH, existing + podBlock, { mode: 0o600 })
}

/**
 * Remove a pod's SSH config entry. Reads current config, filters out the pod,
 * and rewrites.
 */
export function removePodFromSshConfig(podId: string): void {
  if (!existsSync(CONFIG_PATH)) return

  const content = readFileSync(CONFIG_PATH, 'utf-8')
  const lines = content.split('\n')
  const filtered: string[] = []
  let skipping = false

  for (const line of lines) {
    if (line.startsWith(`Host ${CONTAINER_PREFIX}-${podId}`)) {
      skipping = true
      continue
    }
    // A new Host block or non-indented line ends the skip
    if (skipping && (line.startsWith('Host ') || (line.trim() !== '' && !line.startsWith(' ')))) {
      skipping = false
    }
    if (!skipping) {
      filtered.push(line)
    }
  }

  writeFileSync(CONFIG_PATH, filtered.join('\n'), { mode: 0o600 })
}

/**
 * Ensure ~/.ssh/config includes the Wanda SSH config.
 * Adds an Include directive at the top if not already present.
 */
export function ensureSshInclude(): void {
  const sshDir = path.join(os.homedir(), '.ssh')
  mkdirSync(sshDir, { recursive: true, mode: 0o700 })

  const includeLine = `Include ${CONFIG_PATH}`

  if (existsSync(USER_SSH_CONFIG)) {
    const content = readFileSync(USER_SSH_CONFIG, 'utf-8')
    if (content.includes(includeLine)) return
    // Prepend Include directive
    writeFileSync(USER_SSH_CONFIG, `${includeLine}\n\n${content}`, { mode: 0o600 })
  } else {
    writeFileSync(USER_SSH_CONFIG, `${includeLine}\n`, { mode: 0o600 })
  }
}
